services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: