// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT id, isbn
FROM books
WHERE isbn = $1
`

type GetBookByISBNRow struct {
	ID   int32
	Isbn pgtype.Text
}

func (q *Queries) GetBookByISBN(ctx context.Context, isbn pgtype.Text) (GetBookByISBNRow, error) {
	row := q.db.QueryRow(ctx, getBookByISBN, isbn)
	var i GetBookByISBNRow
	err := row.Scan(&i.ID, &i.Isbn)
	return i, err
}

const insertBook = `-- name: InsertBook :exec
INSERT INTO books (isbn, title, description, embedding)
VALUES ($1, $2, $3, $4)
`

type InsertBookParams struct {
	Isbn        pgtype.Text
	Title       string
	Description string
	Embedding   pgvector.Vector
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) error {
	_, err := q.db.Exec(ctx, insertBook,
		arg.Isbn,
		arg.Title,
		arg.Description,
		arg.Embedding,
	)
	return err
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, isbn, title, description, embedding
FROM books
ORDER BY embedding <=> $1
LIMIT 5
`

type SearchBooksRow struct {
	ID          int32
	Isbn        pgtype.Text
	Title       string
	Description string
	Embedding   pgvector.Vector
}

func (q *Queries) SearchBooks(ctx context.Context, embedding pgvector.Vector) ([]SearchBooksRow, error) {
	rows, err := q.db.Query(ctx, searchBooks, embedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksRow
	for rows.Next() {
		var i SearchBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Description,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksByText = `-- name: SearchBooksByText :many
SELECT id, isbn, title, description
FROM books
WHERE tsv @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(tsv, plainto_tsquery('english', $1)) DESC
LIMIT 10
`

type SearchBooksByTextRow struct {
	ID          int32
	Isbn        pgtype.Text
	Title       string
	Description string
}

func (q *Queries) SearchBooksByText(ctx context.Context, plaintoTsquery string) ([]SearchBooksByTextRow, error) {
	rows, err := q.db.Query(ctx, searchBooksByText, plaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksByTextRow
	for rows.Next() {
		var i SearchBooksByTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
