// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/pgvector/pgvector-go"
)

type Book struct {
	ID          int32
	Title       string
	Description string
	Embedding   pgvector.Vector
}
